#!/bin/sh

#/etc/init.d/samba stop

mnt_sta=$(grep /tmp/user /proc/mounts)
[ -n "$mnt_sta" ] && {
	echo "format succeed"
	exit
}
fuser -km /tmp/user

umount /dev/mmcblk0p4
if [ $? -ne 0 ]; then
	echo "format failed"
	exit
fi
usleep 1000000

mkfs.ext4 /dev/mmcblk0p4
if [ $? -ne 0 ]; then
	echo "format failed"
	exit
fi
usleep 100000

mkdir -p /tmp/user
mount -t ext4 /dev/mmcblk0p4 /tmp/user
if [ $? -ne 0 ]; then
	echo "format failed"
	exit
fi

echo "format succeed"

