#!/bin/sh /etc/rc.common

START=98

RUN_D=/tmp/httpd

start() {
	[ -d /tmp/mnt ] || mkdir -p /tmp/mnt
	[ -d $RUN_D ] || mkdir -p $RUN_D
	i=1
	while [ $i -le 10 ]
	do
		mnt_sta=$(grep /tmp/mnt/USB-disk /proc/mounts)
		[ -n "$mnt_sta" ] && {
			break
		}
		sleep 1
		i=$(( $i +1))

	done
	sleep 3
	httpd
}

stop() {
	killall httpd
}
