#!/bin/sh

block umount
if [ $? -ne 0 ]; then
	echo "format failed"
	exit
fi
usleep 1000000

mkfs.vfat /dev/mmcblk0p4
if [ $? -ne 0 ]; then
	echo "format failed"
	exit
fi
usleep 100000

block mount
if [ $? -ne 0 ]; then
	echo "format failed"
	exit
fi

echo "format succeed"

