#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2012 OpenWrt.org

START=90

RUN_D=/var/run/dm_letv

start() {
        
		wifimode=`uci get system.@system[0].wifimode`
		isConnectedAP=`/sbin/route |wc -l`      
	    if [ $isConnectedAP != '5' ];then 
			if [ $wifimode == 'ap' ];then
				/sbin/wifi reload_legacy
			fi
	    fi

		letv_daemon &

}
stop() {
        killall -9 letv_daemon
        killall -9 dm_letv
}
restart() {
		killall -9 letv_daemon
		killall -9 dm_letv
		letv_daemon &
}
