#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

boot() {
	. /lib/netifd/cfg_set.sh
	. /lib/netifd/load_wifi_module.sh

	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	

	mkdir -p /factory
#	mkdir -p /user

	mount -t ext4 /dev/mmcblk0p3 /factory
#	mount -t ext4 /dev/mmcblk0p3 /user
	
	factory_user_set
#	mp_disk write

#	echo /dev/mmcblk0p4 >/sys/devices/platform/jz-dwc2/dwc2/gadget/gadget-lun0/file
#	insmod /lib/modules/3.0.8/g_file_storage.ko stall=0 file=/dev/mmcblk0p4 removable=1

	load_wifi_module
	
#	[ -d /mnt/cfg ] || mkdir -p /mnt/cfg
#	[ -d /mnt/user ] || mkdir -p /mnt/user
#	mount /dev/mmcblk0p2 /mnt/cfg
#	mount /dev/mmcblk0p3 /mnt/user

	/sbin/kmodloader

	# allow wifi modules time to settle
#	sleep 1

#	/sbin/wifi detect > /tmp/wireless.tmp
#	[ -s /tmp/wireless.tmp ] && {
#		cat /tmp/wireless.tmp >> /etc/config/wireless
#	}
#	rm -f /tmp/wireless.tmp

	uci_apply_defaults
	mac=`cfg get mac |awk -F "=" '{print $2}'`
	MAC=$(echo $mac | tr '[a-z]' '[A-Z]')
        #MAC=${mac:0:2}${mac:3:2}${mac:6:2}${mac:9:2}${mac:12:2}${mac:15:2}
        mac1=${MAC:6:6}
        smb_pwd=${MAC:4:8}

        sn=`cfg get qqsn |awk -F "=" '{print $2}'`
	SN=$(echo $sn | tr '[a-z]' '[A-Z]')
	sed -e '/sn/d' -i /tmp/state/status
        echo sn=$SN >> /tmp/state/status
	psk=${SN:8:8}
        wifimode=`uci get system.@system[0].wifimode`
        lehename=`uci get system.@system[0].name`
        flag=`cfg get flag |awk -F "=" '{print $2}'`

	if [ "$lehename" == "" ] && [ "$flag" == "1" ];then
                uci set system.@system[0].name=LEHE$mac1
        fi

        if [ "$wifimode" == "ap" ];then
                uci set wireless.@wifi-iface[0].key=$psk
                #uci set wireless.@wifi-iface[0].key=12345678
                uci set wireless.@wifi-iface[0].ssid=LEHE$mac1
        else
		uci set system.@system[0].wifimode="ap"
		uci commit
		#/sbin/sw.sh sta;
                #uci set wireless.@wifi-iface[0].p2p_go_ssid=DIRECT-LEHE$mac1
                #uci set wireless.@wifi-iface[0].p2p_go_key=$psk
                #uci set wireless.@wifi-iface[0].p2p_go_key=12345678

        fi

	wifimode_btn=`get_wifimode_btn`
	if [ "$wifimode_btn" = "2g" ];then
		uci set wireless2.@wifi[0].mode=2g
	else
		uci set wireless2.@wifi[0].mode=5g
	fi

        uci commit
        smbpwd=`uci get samba.@samba[0].password`
        if [ "$smbpwd" == "" ];then

                uci set samba.@samba[0].password=$smb_pwd
                uci set samba.@samba[0].guest_password=$psk
	        uci commit
		
        fi
	
	# temporary hack until configd exists
	/sbin/reload_config

	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}

	#check mpset flag, if not mpset, use default ssid
	# maybe need TODO

	#check upgrade flag , if yes, use the user set
#	local upgrade=$(uci -c/mnt/cfg/etc/config get system.upgrade[0].status 2>/dev/null)
#	if [ "$upgrade" = "1" ]; then
#		cp -f /mnt/user/etc/config/* /etc/config/
#		uci -c/mnt/cfg/etc/config set system.upgrade[0].status=0
#		uci -c/mnt/cfg/etc/config commit system

#	fi
}
