/* Automatically generated by configure - do not modify! */
#define VERSION "1.0.0-DAMAI"
#define PACKAGE "shairport"
#define PACKAGE_NAME "Shairport"
#define SYSCONFDIR "/etc"
#define LOCALEDIR "/usr/share/locale"

/* Shairport config.h in detail */
#undef CONFIG_SNDIO
#undef CONFIG_AO
#undef CONFIG_PULSE
#undef CONFIG_ALSA
#define CONFIG_OSS
#undef FANCY_RESAMPLING
#undef CONFIG_AVAHI
#define CONFIG_FASTMDNS
#define CONFIG_TINYSVCMDNS
#define CONFIG_MUTEBUFFER_ADJUST
#undef CONFIG_HAVE_DNS_SD_H
#define CONFIG_HAVE_GETOPT_H
